import {PERMISSIONS} from 'react-native-permissions';

export const ANDROID_PERMISSION_LIST = [
  PERMISSIONS.ANDROID.CAMERA,
  PERMISSIONS.ANDROID.READ_MEDIA_IMAGES,
  PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,
  PERMISSIONS.ANDROID.ACCESS_COARSE_LOCATION,
  PERMISSIONS.ANDROID.ACCESS_BACKGROUND_LOCATION,
];

export const IOS_PERMISSION_LIST = [
  PERMISSIONS.IOS.CAMERA,
  PERMISSIONS.IOS.PHOTO_LIBRARY,
  PERMISSIONS.IOS.LOCATION_WHEN_IN_USE,
  PERMISSIONS.IOS.LOCATION_ALWAYS,
]